### ISSUE TITLE
Provide pin code to finishProcess

### ISSUE THREAD

**Issue by zpalmtree** [fnzc/react-native-pincode#63]
If we're using `enter` mode, we can use `endProcessFunction` to get the entered pin code:

```
<PINCode
    status={'enter'}
    endProcessFunction={(pin) => console.log('Got pin: ' + pin)}}
/>
```

However, if we're using `choose` mode, I'm not seeing a simple way to get the correct pin code. We can use `finishProcess` to indicate when the correct pin has been entered, but this doesn't provide the pin code.

I could use `storePin` and then store the pin myself, but it would be a bit nicer if `finishProcess` could come with the pin :)

Hopefully I'm not overlooking a simple way to do this.

Thanks for the great library!

**Comment by Haskkor** [comment]
Hi there!

Thanks for the feedback.
You could use `endProcessFunction` that provides the pin code but you would then need to handle all the process by yourself (go to lock page etc...).
I'll had the pinCode in the finishProcess anyway as it seems to be a good idea :).

Cheers,
Jeremy

**Comment by Haskkor** [comment]
Done in the latest version :)

**Comment by zpalmtree** [comment]
Just checked it out, I think you forgot to pass the pinCode parameter in the Choose version - 
```
if (!!this.props.finishProcess) this.props.finishProcess();
```

probably should be

```
if (!!this.props.finishProcess) this.props.finishProcess(pinCode);
```

https://github.com/fnzc/react-native-pincode/commit/73accb7d4203e6ae0b3ca564f75dc59c1c1cf8b6#diff-8d409b6084f279038462b9cbdc4ed0b2R96

Thanks.

**Comment by zpalmtree** [comment]
Maybe I'm being stupid, but perhaps you forgot to rebuild the generated JavaScript? Checking in `dist/src/PinCodeEnter.js` and `dist/src/PinCodeChoose.js`, both `finishProcess` functions are missing their arguments. The function works as expected after modifying the generated JS.

Thanks.

**Comment by Haskkor** [comment]
F*** sake I'm so sorry. 
I'm doing something else at the same time...
Fixing it now 🙈 😅

**Comment by Haskkor** [comment]
Done

**Comment by zpalmtree** [comment]
Thank you, it happens to all of us :smile:
